# Generated by Django 6.0.5 on 2026-06-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_dns", "0031_record_netbox_dns_record_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="expiration_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
